import json
from pathlib import Path
import pandas as pd
O=Path('/home/cas/fyp_place_recognition/outputs/canonical_v2/06_vlm');T=80
m=pd.read_csv(O/'case_manifest.csv');d=pd.read_csv(O/'vlm_decisions.csv');pool=pd.read_csv(O/'pool_status.csv').set_index('query_frame').pool_status.to_dict();keys=['query_frame','case_type','anchor_frame','challenger_frame','order','candidate_A_frame','candidate_B_frame'];x=d.merge(m,on=keys,validate='one_to_one',suffixes=('','_m'));pairs=[]
for key,g in x.groupby(['query_frame','case_type','anchor_frame','challenger_frame'],sort=True):
 ab=g[g.order=='AB'].iloc[0];ba=g[g.order=='BA'].iloc[0];af=int(ab.chosen_frame) if pd.notna(ab.chosen_frame) else None;bf=int(ba.chosen_frame) if pd.notna(ba.chosen_frame) else None;raw=ab.choice in {'A','B'} and ba.choice in {'A','B'} and af==bf and af is not None;winner=af if raw else None;conf=min(int(ab.confidence),int(ba.confidence));act=raw and conf>=T;row=g.iloc[0];wp=None
if raw:wp=int(row.candidate_A_is_positive) if winner==int(row.candidate_A_frame) else int(row.candidate_B_is_positive) if winner==int(row.candidate_B_frame) else None
pairs.append({'query_frame':int(key[0]),'case_type':key[1],'anchor_frame':int(key[2]),'challenger_frame':int(key[3]),'AB_choice':ab.choice,'BA_choice':ba.choice,'AB_chosen_frame':af,'BA_chosen_frame':bf,'RAW_CONSISTENT_WINNER':winner,'HIGH_CONFIDENCE_ACTIONABLE_WINNER':winner if act else None,'raw_consistent_winner':raw,'high_confidence_actionable_winner':act,'min_confidence':conf,'winner_is_positive':wp,'anchor_is_positive':int(row.anchor_is_positive),'challenger_is_positive':int(row.challenger_is_positive),'api_success_pair':bool(ab.api_success) and bool(ba.api_success)})
p=pd.DataFrame(pairs);p.to_csv(O/'pair_evaluation.csv',index=False);qrows=[]
for q,g in p.groupby('query_frame',sort=True):
 anchor_pos=bool(g.iloc[0].anchor_is_positive);chall=g[(g.high_confidence_actionable_winner)&(g.HIGH_CONFIDENCE_ACTIONABLE_WINNER==g.challenger_frame)];frames=sorted(chall.HIGH_CONFIDENCE_ACTIONABLE_WINNER.dropna().astype(int).unique());override=len(frames)==1;sel=frames[0] if override else None;selpos=(bool(int(chall[chall.HIGH_CONFIDENCE_ACTIONABLE_WINNER==sel].iloc[0].winner_is_positive)) if override else None);rawpos=g[(g.raw_consistent_winner)&(g.RAW_CONSISTENT_WINNER==g.challenger_frame)&(g.winner_is_positive==1)];corr=bool(override and not anchor_pos and selpos);reg=bool(override and anchor_pos and not selpos);status=pool[int(q)];action='CANONICAL_TOP20_POOL_MISS' if status=='CANONICAL_TOP20_POOL_MISS' else 'OVERRIDE_SC' if override else 'KEEP_SC';qrows.append({'query_frame':int(q),'pool_status':status,'anchor_is_positive':anchor_pos,'raw_positive_challengers':json.dumps([int(z) for z in rawpos.RAW_CONSISTENT_WINNER.dropna().unique()]),'deployment_actionable_challenger':sel,'actionable_winner_is_positive':selpos,'threshold_abstained_correct':bool(len(rawpos) and not override),'action':action,'system_correction':corr,'system_regression':reg})
qdf=pd.DataFrame(qrows);qdf.to_csv(O/'query_evaluation.csv',index=False);cms=[]
for typ,g in p.groupby('case_type'):cms.append({'case_type':typ,'comparisons':len(g),'api_success_rate':g.api_success_pair.mean(),'ab_ba_consistency_rate':g.raw_consistent_winner.mean(),'abstention_rate':1-g.high_confidence_actionable_winner.mean(),'raw_positive_winner_rate':((g.raw_consistent_winner)&(g.winner_is_positive==1)).mean(),'actionable_positive_winner_rate':((g.high_confidence_actionable_winner)&(g.winner_is_positive==1)).mean()})
pd.DataFrame(cms).to_csv(O/'case_metrics.csv',index=False);c=int(qdf.system_correction.sum());r=int(qdf.system_regression.sum());pm=int((qdf.pool_status=='CANONICAL_TOP20_POOL_MISS').sum());rawrej=int(qdf.threshold_abstained_correct.sum());system=149+c-r;cls='SELECTIVE_VLM_ADDS_VALUE' if c>=1 and r==0 else 'VLM_VERIFICATION_INTRODUCES_TOO_MANY_REGRESSIONS' if r>c else 'VLM_USEFUL_BUT_CONFIDENCE_OR_STABILITY_LIMITED' if rawrej else 'VLM_SEMANTIC_VERIFICATION_NOT_EFFECTIVE';lines=['# Canonical Selective VLM Evaluation','',f'Candidate filtering ceiling: {pm} canonical Top20 pool misses.',f'AB/BA consistency: {p.raw_consistent_winner.mean():.6f}',f'Actionable rate: {p.high_confidence_actionable_winner.mean():.6f}',f'Corrections: {c}',f'Regressions: {r}',f'Net gain: {c-r}',f'System R@1: {system}/158 = {system/158:.6f}',f'Threshold-abstained raw positive decisions: {rawrej}',f'Classification: {cls}'];(O/'summary.txt').write_text('\n'.join(lines)+'\n');print('\n'.join(lines))
