/* Generic Demo V1 architecture. Message objects are local stand-ins for future transport. */
class ReplayEvent{constructor(x){Object.assign(this,x)}}
class RobotAgent{constructor(x,color){Object.assign(this,x);this.color=color;this.displayState={progress:0}}}
class InterRobotLoop{constructor(x){Object.assign(this,x)}}
class DemoState{constructor(data){this.mode=data.mode;this.progress=0;this.playing=false;this.speed=1;this.showLoops=false;this.agents=data.agents.map((x,i)=>new RobotAgent(x,['#4cc9f0','#f8961e','#c77dff','#80ed99'][i%4]));this.events=data.events.map(x=>new ReplayEvent(x));this.global=data.global_trajectory;this.map=data.map_points;this.meta=data.metadata}}
class RingKeyMessage{} class CandidateRequest{} class DescriptorResponse{} class PointCloudRequest{} class LoopConstraintMessage{} class OptimizationUpdate{}
class CentralCoordinator{constructor(state){this.state=state;this.globalDescriptorDatabase=new Map();this.acceptedLoops=[];this.optimizationState='READY'} update(){let s=this.state;this.acceptedLoops=s.events.filter(e=>e.progress<=s.progress);this.optimizationState=s.progress<.78?'READY':s.progress<.92?'OPTIMIZING':'COMPLETE';}}
let S,C,ctx,mctx,last=0;const $=x=>document.querySelector(x);
fetch('data/replay.json').then(r=>r.json()).then(data=>{S=new DemoState(data);C=new CentralCoordinator(S);ctx=$('#canvas').getContext('2d');mctx=$('#map').getContext('2d');bind();draw();requestAnimationFrame(tick)});
function bind(){$('#play').onclick=()=>{S.playing=!S.playing;$('#play').textContent=S.playing?'Pause':'Play'};$('#reset').onclick=()=>{S.progress=0;S.playing=false;$('#play').textContent='Play';draw()};$('#speed').onchange=e=>S.speed=+e.target.value;$('#timeline').oninput=e=>{S.progress=e.target.value/1000;draw()};document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{S.progress=+b.dataset.jump;draw()});$('#allloops').onchange=e=>{S.showLoops=e.target.checked;draw()}}
function tick(t){if(S&&S.playing){S.progress=Math.min(1,S.progress+(t-last)/24000*S.speed);if(S.progress>=1)S.playing=false;draw()}last=t;requestAnimationFrame(tick)}
function xy(u,v,w,h){return[35+u*(w-70),h-35-v*(h-70)]}function line(c,a,b,col,alpha=1){c.globalAlpha=alpha;c.strokeStyle=col;c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke();c.globalAlpha=1}
function draw(){if(!S)return;C.update();$('#timeline').value=Math.round(S.progress*1000);$('#time').textContent=`Replay time ${(S.progress*100).toFixed(1)}%`;let w=ctx.canvas.width,h=ctx.canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#07101c';ctx.fillRect(0,0,w,h);let groups={};S.global.forEach(p=>(groups[p.robot_id]??=[]).push(p));Object.entries(groups).forEach(([id,a],i)=>{ctx.strokeStyle=S.agents.find(x=>x.robot_id===id)?.color||'#fff';ctx.lineWidth=2;ctx.beginPath();a.forEach((p,j)=>{let q=xy(p.u,p.v,w,h);j?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.stroke()});let ev=C.acceptedLoops;let shown=S.showLoops?ev:ev.slice(-1);shown.forEach((e,i)=>{let a=S.global.find(p=>p.robot_id===e.source_robot&&p.keyframe_id===e.source_keyframe),b=S.global.find(p=>p.robot_id===e.target_robot&&p.keyframe_id===e.target_keyframe);if(a&&b)line(ctx,xy(a.u,a.v,w,h),xy(b.u,b.v,w,h),i===shown.length-1?'#57cc99':'#88a',i===shown.length-1?1:.12)});ctx.fillStyle='#b7d4f1';ctx.fillText(S.progress<.18?'SCENE 1 — separate local estimates':S.progress<.78?'SCENE 2–3 — inter-robot constraints':S.progress<.92?'SCENE 4 — GLOBAL POSE GRAPH':'SCENE 5 — MAP MERGE',18,22);drawMap();panel()}
function drawMap(){let w=mctx.canvas.width,h=mctx.canvas.height;mctx.clearRect(0,0,w,h);let pts=S.map;let xs=pts.map(x=>x[0]),ys=pts.map(x=>x[1]),lo=[Math.min(...xs),Math.min(...ys)],sp=[Math.max(...xs)-lo[0],Math.max(...ys)-lo[1]];mctx.fillStyle='#85b7dc';pts.forEach(p=>{let q=xy((p[0]-lo[0])/sp[0],(p[1]-lo[1])/sp[1],w,h);mctx.fillRect(q[0],q[1],1,1)})}
function panel(){let e=C.acceptedLoops.at(-1), candidate=e?`<span class="candidate">Candidate — geometry not verified</span> → <span class="accepted">ACCEPTED</span>`:'Waiting for frozen event';$('#event').innerHTML=e?`<table><tr><td>Query</td><td>${e.source_robot} #${e.source_keyframe}</td></tr><tr><td>Candidate</td><td>${e.target_robot} #${e.target_keyframe}</td></tr><tr><td>SC score / rank</td><td>${e.sc_score.toFixed(4)} / ${e.sc_rank}</td></tr><tr><td>best shift / SC yaw</td><td>${e.best_shift} / ${e.sc_yaw_deg.toFixed(2)}°</td></tr><tr><td>GICP quality</td><td>${e.gicp_quality.toFixed(4)} (threshold 0.6091)</td></tr><tr><td>Transform</td><td>T_query_from_candidate; p_query = T · p_candidate</td></tr></table>${candidate}`:'No loop event yet';let m=S.meta;$('#status').innerHTML=`<table><tr><td>Robot count</td><td>${S.agents.length}</td></tr><tr><td>Accepted sanitized loops</td><td>${C.acceptedLoops.length} / ${m.rank1_sanitized_loops}</td></tr><tr><td>Graph</td><td>${m.nodes} nodes · ${m.odometry_factors} odometry · ${m.inter_robot_loops} loops</td></tr><tr><td>Backend</td><td>GTSAM Pose3 · Huber ${m.huber_delta}</td></tr><tr><td>PGO state</td><td>${C.optimizationState}</td></tr><tr><td>Measured offline solve time</td><td>${m.measured_offline_solve_time_s.toFixed(2)} s</td></tr></table>`;$('#messages').textContent=e?`${e.source_robot} → server: RingKeyMessage\nserver → ${e.source_robot}: CandidateRequest\n${e.source_robot} / ${e.target_robot} → server: PointCloudResponse\nserver: LoopConstraint accepted`:'No transport event replayed yet'}
